// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVQRm_yDBQsA5MEZORauPLYE1E7-B6Sc',
    appId: '1:11767948944:web:954134919d4e021280da15',
    messagingSenderId: '11767948944',
    projectId: 'games-hub-31131',
    authDomain: 'games-hub-31131.firebaseapp.com',
    storageBucket: 'games-hub-31131.firebasestorage.app',
    measurementId: 'G-564NE8SBVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9jjgL66WQbplVbpwEX576RqOkBj_ORTI',
    appId: '1:11767948944:android:444318a39e77bdae80da15',
    messagingSenderId: '11767948944',
    projectId: 'games-hub-31131',
    storageBucket: 'games-hub-31131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkcCxhFMaSn-f39-thAIrZMC3gvB1M38',
    appId: '1:11767948944:ios:21d82230e8742d6980da15',
    messagingSenderId: '11767948944',
    projectId: 'games-hub-31131',
    storageBucket: 'games-hub-31131.firebasestorage.app',
    iosClientId: '11767948944-88g9ulib64v7jmhhhn6ks1o2co5uica4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationGameshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvkcCxhFMaSn-f39-thAIrZMC3gvB1M38',
    appId: '1:11767948944:ios:21d82230e8742d6980da15',
    messagingSenderId: '11767948944',
    projectId: 'games-hub-31131',
    storageBucket: 'games-hub-31131.firebasestorage.app',
    iosClientId: '11767948944-88g9ulib64v7jmhhhn6ks1o2co5uica4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationGameshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnVQRm_yDBQsA5MEZORauPLYE1E7-B6Sc',
    appId: '1:11767948944:web:8dd14f4debffa65c80da15',
    messagingSenderId: '11767948944',
    projectId: 'games-hub-31131',
    authDomain: 'games-hub-31131.firebaseapp.com',
    storageBucket: 'games-hub-31131.firebasestorage.app',
    measurementId: 'G-JC14D7YFBN',
  );
}
