import 'package:flutter/material.dart';
// 1. New Imports for Firebase
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Ensure this file was generated by flutterfire configure

// 2. Import your screens
import 'screens/homes.dart';
import 'screens/login_register_page.dart'; // We will create this next

void main() async {
  // 3. Initialize Firebase
  // This line is essential for any Firebase service to work.
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const GamesHubApp());
}

// GamesHubApp is kept the same, but its home property will be the AuthChecker
class GamesHubApp extends StatelessWidget {
  const GamesHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Games Hub',
      theme: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.deepPurple,
        scaffoldBackgroundColor: const Color(0xFF0D022F),
      ),
      // 4. Change the home to the AuthChecker
      home: const AuthChecker(),
      debugShowCheckedModeBanner: false,
    );
  }
}

// ----------------------------------------------------
// 5. Create the Authentication Checker Widget (AuthChecker)
// ----------------------------------------------------
class AuthChecker extends StatelessWidget {
  const AuthChecker({super.key});

  @override
  Widget build(BuildContext context) {
    // StreamBuilder listens to the authentication state changes (login/logout)
    return StreamBuilder<User?>(
      // FirebaseAuth.instance.authStateChanges() yields a User object
      // when logged in, or null when logged out.
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Show a loading indicator while Firebase checks the user status
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // If data exists (snapshot.hasData == true) and the User object is not null
        if (snapshot.hasData) {
          // User is logged in, show the game dashboard
          return const HomeScreen();
        } else {
          // User is logged out, show the login/register page
          return const LoginRegisterPage();
        }
      },
    );
  }
}
